### ISSUE TITLE
error while running maaslin2 in R

### ISSUE THREAD

**Issue by negin1986** [biobakery/Maaslin2#1]
Hi all,

Here is the error I get when I run maaslin2 in R. I was able to run it in Galaxy using pcl file, though. Don't know why says values are character.

> fit_data = Maaslin2(pathabundance_relab, metadata_t, "results/2018-06-29-seq-QC-and-trimming/HUMANn2/pathabundance/MaAsLin")
[1] "Warning: Deleting existing log file: results/2018-06-29-seq-QC-and-trimming/HUMANn2/pathabundance/MaAsLin/maaslin2.log"
2019-07-22 18:43:54 INFO::Writing function arguments to log file
2019-07-22 18:43:54 INFO::Verifying options selected are valid
2019-07-22 18:43:54 INFO::Determining format of input files
2019-07-22 18:43:54 INFO::Input format is data samples as columns and metadata samples as columns
2019-07-22 18:43:55 INFO::Formula for fixed effects: expr ~  SampleID + FeedingType + DeliveryMode + Comments
2019-07-22 18:43:55 INFO::Running selected normalization method: TSS
Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument
In addition: Warning message:
In vegan::decostand(features_norm, method = "total", MARGIN = 1,  :
  input data contains negative entries: result may be non-sense

**Comment by himelmallick** [comment]
Hi @negin1986 - sorry for the delay in getting back to you. Could you please send a minimum reproducible example so that I can debug?

**Comment by jmlue** [comment]
Having similar error, curious if this was ever figured out?

**Comment by tamburinif** [comment]
I had the same `Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument` error when I was trying to run Maaslin2 by supplying data frames as input instead of the string filepaths to the input files as in the demo (running in Rstudio).

I got a different error when I tried to read the demo files into data frames and run Maaslin2. To me, it seems ideal that the function would accept either data frames or filepaths as input.

**Comment by yilmazbah** [comment]
Aynone had a solution for this? Did you manage to run it?

**Comment by yilmazbah** [comment]
I have tried with your example files too and have the same output error:

2020-01-27 17:56:16 INFO::Running selected normalization method: TSS
**Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument
In addition: Warning message:
In vegan::decostand(features_norm, method = "total", MARGIN = 1,  :
  input data contains negative entries: result may be non-sense**

Have no idea what's happening because I was using it until recently.

Thank you so much for the help.

Bahti

**Comment by jacodela** [comment]
I have had the same issue, even with the test data the package provides, but only when the input is a data frame from R; otherwise it works when providing the path to a file. I found a workaround by writing my tables to a tmp file and then executing the function, although it is kind of annoying having to do this

```
# Write files to tmp and execute
tmp_data = tempfile(pattern = "data")
write_delim(Relabund_data, tmp_data, delim = "\t")


tmp_metadata = tempfile(pattern = "metadata")
write_delim(Metadata_LMs, tmp_metadata, delim = "\t")

fit_data <- Maaslin2(tmp_data, tmp_metadata, "out/dir")
```

**Comment by yilmazbah** [comment]
Dear Jacobo,
Thank you so much. Actually I managed to do as you suggested. I am so sorry that I forgot to add my working commands here. But I really appreciate your help too.
Cheers,
Bahti
